spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ponto_inteligente?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: select 1  
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      
  flyway:
    enabled: false
    
  data:
    rest:
      basePath: /api
  
  profiles:
    active:
    - dev 
pagina:
  quantidade_pagina: 25
